name: Hexo GitHub Pages

on:
  push:
    branches:
      - main  # 你代码主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2️⃣ 使用 Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 3️⃣ 缓存 npm 依赖
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      # 4️⃣ 安装 Hexo CLI、依赖和主题
      - name: Install Dependencies
        run: |
          npm i -g hexo-cli
          npm install
          npm install hexo-theme-landscape@latest

      # 5️⃣ 构建 Hexo 网站
      - name: Build Hexo Site
        run: |
          hexo clean
          hexo generate
          # 禁用 Jekyll
          touch ./public/.nojekyll

      # 6️⃣ 上传生成的 public 文件夹作为 artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
